import { VaultItem, SecureNoteItem, SharedVaultItem, ActivityAuditItem, PasswordFolder } from "./types";

export const INITIAL_VAULT_ITEMS: VaultItem[] = [
  {
    id: "vault-1",
    title: "Google",
    username: "roshan.singh@gmail.com",
    password: "K9#pL7@xQ!2mnN$zR8",
    website: "https://accounts.google.com",
    category: "Work",
    folder: "Social Media",
    notes: "My primary Google account for workspace, photos, and backups.",
    strength: "very_strong",
    isFavorite: true,
    isCompromised: false,
    isReused: false,
    lastModified: "14 May 2025, 9:30 AM",
    createdAt: "10 Jan 2024, 7:15 PM",
    brandColor: "#4285F4",
    iconName: "google",
  },
  {
    id: "vault-2",
    title: "Facebook",
    username: "roshan.singh@gmail.com",
    password: "fB_#982*mQx!vP71",
    website: "https://www.facebook.com",
    category: "Social Media",
    folder: "Social Media",
    notes: "Personal social networking profile.",
    strength: "strong",
    isFavorite: true,
    isCompromised: false,
    isReused: false,
    lastModified: "12 May 2025, 3:10 PM",
    createdAt: "15 Feb 2023, 2:00 PM",
    brandColor: "#1877F2",
    iconName: "facebook",
  },
  {
    id: "vault-3",
    title: "Instagram",
    username: "roshan_singh_07",
    password: "Ig_2025@SecureX9",
    website: "https://www.instagram.com",
    category: "Social Media",
    folder: "Social Media",
    notes: "Photography and personal creator page.",
    strength: "strong",
    isFavorite: false,
    isCompromised: false,
    isReused: false,
    lastModified: "13 May 2025, 10:20 PM",
    createdAt: "04 May 2023, 11:20 AM",
    brandColor: "#E1306C",
    iconName: "instagram",
  },
  {
    id: "vault-4",
    title: "Amazon",
    username: "roshan.singh@gmail.com",
    password: "Amz_Shop#2026!7x",
    website: "https://www.amazon.com",
    category: "Shopping",
    folder: "Shopping",
    notes: "Prime subscription and family deliveries.",
    strength: "very_strong",
    isFavorite: false,
    isCompromised: false,
    isReused: false,
    lastModified: "14 May 2025, 9:15 AM",
    createdAt: "22 Nov 2022, 4:45 PM",
    brandColor: "#FF9900",
    iconName: "amazon",
  },
  {
    id: "vault-5",
    title: "Netflix",
    username: "roshan.singh@gmail.com",
    password: "password123",
    website: "https://www.netflix.com",
    category: "Personal",
    folder: "Personal",
    notes: "4K UHD Family streaming plan.",
    strength: "weak",
    isFavorite: false,
    isCompromised: false,
    isReused: true,
    lastModified: "08 May 2025, 6:00 PM",
    createdAt: "19 Aug 2022, 8:15 PM",
    brandColor: "#E50914",
    iconName: "netflix",
  },
  {
    id: "vault-6",
    title: "PayPal",
    username: "roshan.singh@gmail.com",
    password: "P$9#kL2!wQ8*zR5v",
    website: "https://www.paypal.com",
    category: "Banking",
    folder: "Banking",
    notes: "International transactions and medical software billing.",
    strength: "very_strong",
    isFavorite: false,
    isCompromised: false,
    isReused: false,
    lastModified: "14 May 2025, 8:50 AM",
    createdAt: "01 Mar 2023, 1:10 PM",
    brandColor: "#003087",
    iconName: "paypal",
  },
  {
    id: "vault-7",
    title: "Twitter / X",
    username: "roshan_singh_07",
    password: "Tw_#782!xP9q0L1",
    website: "https://twitter.com",
    category: "Social Media",
    folder: "Social Media",
    notes: "Tech news and Care2Care public updates.",
    strength: "strong",
    isFavorite: false,
    isCompromised: false,
    isReused: false,
    lastModified: "09 May 2025, 2:30 PM",
    createdAt: "10 Jun 2022, 10:00 AM",
    brandColor: "#1DA1F2",
    iconName: "twitter",
  },
  {
    id: "vault-8",
    title: "Spotify",
    username: "roshan.singh@gmail.com",
    password: "password123",
    website: "https://www.spotify.com",
    category: "Personal",
    folder: "Personal",
    notes: "Workout and meditation focus playlists.",
    strength: "weak",
    isFavorite: false,
    isCompromised: false,
    isReused: true,
    lastModified: "05 May 2025, 4:00 PM",
    createdAt: "12 Dec 2022, 9:20 PM",
    brandColor: "#1DB954",
    iconName: "spotify",
  },
];

export const INITIAL_FOLDERS: PasswordFolder[] = [
  { id: "all", name: "All Items", icon: "📁", itemCount: 128, color: "#FF5A36" },
  { id: "work", name: "Work", icon: "💼", itemCount: 32, color: "#FF8B6B" },
  { id: "social", name: "Social Media", icon: "📱", itemCount: 18, color: "#1877F2" },
  { id: "banking", name: "Banking", icon: "🏦", itemCount: 12, color: "#10B981" },
  { id: "shopping", name: "Shopping", icon: "🛍️", itemCount: 10, color: "#F59E0B" },
  { id: "personal", name: "Personal", icon: "👤", itemCount: 15, color: "#8B5CF6" },
  { id: "unfiled", name: "No Folder", icon: "📂", itemCount: 13, color: "#64748B" },
];

export const INITIAL_SECURE_NOTES: SecureNoteItem[] = [
  {
    id: "note-1",
    title: "Wi-Fi Router Credentials",
    preview: "SSID: Home_Fiber_5G | WPA3 Key: #Hyper7_Zen!982",
    content: "SSID: Home_Fiber_5G\nWPA3 Key: #Hyper7_Zen!982\nAdmin URL: 192.168.1.1\nAdmin Pass: AdminCare2Care!2026",
    category: "Utilities",
    folder: "Personal",
    isFavorite: true,
    lastModified: "14 May 2025",
    date: "14 May 2025",
  },
  {
    id: "note-2",
    title: "Passport Details",
    preview: "Passport No: Z9283741 | Exp: 12 Aug 2032 | Country: USA",
    content: "Passport No: Z9283741\nIssue Date: 12 Aug 2022\nExpiry Date: 12 Aug 2032\nFull Name: Roshan Singh",
    category: "Identity",
    folder: "Personal",
    isFavorite: false,
    lastModified: "10 May 2025",
    date: "10 May 2025",
  },
  {
    id: "note-3",
    title: "Software License Keys",
    preview: "Care2Care Pro Enterprise Key: C2C-ENT-9948-X710-PL",
    content: "Care2Care Pro Enterprise Key: C2C-ENT-9948-X710-PL\nAdobe CC: 4492-8819-2001-9923\nJetBrains IDE: JB-COMM-2026-X8",
    category: "Work",
    folder: "Work",
    isFavorite: true,
    lastModified: "06 May 2025",
    date: "06 May 2025",
  },
  {
    id: "note-4",
    title: "Recovery Information",
    preview: "Master Backup 24-Word Seed Phrase for Offline Vault",
    content: "Seed Phrase: arctic breeze timber meadow flame pulse orbit vibrant crystal summit lotus feather shield echo quartz beacon harbor crown dynamic river valley spark crest anchor",
    category: "Security",
    folder: "Work",
    isFavorite: false,
    lastModified: "28 Apr 2025",
    date: "28 Apr 2025",
  },
  {
    id: "note-5",
    title: "Important Codes",
    preview: "Safe Combination: 42-18-91 | Locker PIN: 8820",
    content: "Master Safe Dial: 42 - 18 - 91\nHome Gym Locker PIN: 8820\nOffice Gate Passcode: #4092*",
    category: "Personal",
    folder: "Personal",
    isFavorite: true,
    lastModified: "20 Apr 2025",
    date: "20 Apr 2025",
  },
];

export const INITIAL_SHARED_ITEMS: SharedVaultItem[] = [
  {
    id: "sh-1",
    title: "Netflix Account",
    sharedWith: ["sarah.k@gmail.com", "david.m@gmail.com"],
    sharedBy: "roshan.singh@gmail.com",
    accessLevel: "read",
    sharedDate: "14 May 2025",
    icon: "netflix",
    type: "sent",
  },
  {
    id: "sh-2",
    title: "Home Wi-Fi",
    sharedWith: ["mom.care@gmail.com"],
    sharedBy: "roshan.singh@gmail.com",
    accessLevel: "read",
    sharedDate: "14 May 2025",
    icon: "wifi",
    type: "sent",
  },
  {
    id: "sh-3",
    title: "Disney+ Account",
    sharedWith: ["emma.w@gmail.com", "chris.t@gmail.com", "lucas.p@gmail.com"],
    sharedBy: "roshan.singh@gmail.com",
    accessLevel: "read",
    sharedDate: "13 May 2025",
    icon: "disney",
    type: "sent",
  },
  {
    id: "sh-4",
    title: "Office Email",
    sharedWith: ["team.assist@care2care.org", "director@care2care.org"],
    sharedBy: "roshan.singh@gmail.com",
    accessLevel: "edit",
    sharedDate: "28 Apr 2025",
    icon: "mail",
    type: "sent",
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityAuditItem[] = [
  {
    id: "act-1",
    action: 'Password "Google" viewed',
    targetItem: "Google",
    timestamp: "14 May 2025, 9:30 AM",
    device: "This Device",
    type: "view",
  },
  {
    id: "act-2",
    action: 'Password "Amazon" copied',
    targetItem: "Amazon",
    timestamp: "14 May 2025, 9:15 AM",
    device: "This Device",
    type: "copy",
  },
  {
    id: "act-3",
    action: 'New item added "PayPal"',
    targetItem: "PayPal",
    timestamp: "14 May 2025, 8:50 AM",
    device: "This Device",
    type: "create",
  },
  {
    id: "act-4",
    action: 'Item "Instagram" edited',
    targetItem: "Instagram",
    timestamp: "13 May 2025, 10:20 PM",
    device: "This Device",
    type: "edit",
  },
  {
    id: "act-5",
    action: "Logged in",
    targetItem: "Master Vault",
    timestamp: "14 May 2025, 7:45 AM",
    device: "Android App",
    type: "login",
  },
  {
    id: "act-6",
    action: "Exported data",
    targetItem: "Encrypted Backup",
    timestamp: "12 May 2025, 6:10 PM",
    device: "This Device",
    type: "export",
  },
];
