import { ExerciseItem, WorkoutPlan, WorkoutProgram, BodyStatMeasurement } from "./types";

export const INITIAL_EXERCISES: ExerciseItem[] = [
  {
    id: "ex-1",
    name: "Push Up",
    category: "Bodyweight",
    bodyPart: "Chest",
    difficulty: "Beginner",
    equipment: ["Bodyweight", "Mat"],
    musclesWorked: ["Chest (Pectorals)", "Triceps", "Anterior Deltoids", "Core"],
    instructions: [
      "Place hands shoulder-width apart on the floor with fingers spread.",
      "Keep body in a rigid straight line from head to heels.",
      "Lower your chest until it is about an inch from the floor.",
      "Push back up explosively to starting position while engaging core."
    ],
    sets: 3,
    reps: 12,
    weightKg: 0,
    restSeconds: 60,
    isFavorite: true,
  },
  {
    id: "ex-2",
    name: "Dumbbell Bench Press",
    category: "Strength",
    bodyPart: "Chest",
    difficulty: "Intermediate",
    equipment: ["Dumbbells", "Bench"],
    musclesWorked: ["Chest", "Shoulders", "Triceps"],
    instructions: [
      "Lie flat on a sturdy bench holding dumbbells at chest level.",
      "Press the dumbbells up until arms are fully extended without locking elbows.",
      "Slowly lower back down with control to starting position."
    ],
    sets: 4,
    reps: 10,
    weightKg: 20,
    restSeconds: 60,
    isFavorite: true,
  },
  {
    id: "ex-3",
    name: "Bent Over Row",
    category: "Strength",
    bodyPart: "Back",
    difficulty: "Intermediate",
    equipment: ["Barbell / Dumbbells"],
    musclesWorked: ["Latissimus Dorsi", "Rhomboids", "Biceps", "Rear Delts"],
    instructions: [
      "Hinge at hips with flat back, knees slightly bent at 45 degrees.",
      "Pull weight smoothly towards lower ribcage, squeezing shoulder blades.",
      "Lower with controlled eccentric tempo."
    ],
    sets: 3,
    reps: 12,
    weightKg: 25,
    restSeconds: 60,
    isFavorite: true,
  },
  {
    id: "ex-4",
    name: "Dumbbell Row",
    category: "Strength",
    bodyPart: "Back",
    difficulty: "Intermediate",
    equipment: ["Dumbbell", "Bench"],
    musclesWorked: ["Lats", "Rhomboids", "Biceps"],
    instructions: [
      "Place one knee and hand on bench for solid stabilization.",
      "Pull dumbbell up towards hip crease keeping elbow tucked close.",
      "Pause briefly at peak contraction and lower smoothly."
    ],
    sets: 3,
    reps: 12,
    weightKg: 16,
    restSeconds: 60,
    isFavorite: false,
  },
  {
    id: "ex-5",
    name: "Squat",
    category: "Strength",
    bodyPart: "Legs",
    difficulty: "Beginner",
    equipment: ["Barbell / Bodyweight"],
    musclesWorked: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    instructions: [
      "Stand with feet shoulder-width apart, toes flared slightly outwards.",
      "Break at hips and knees, sitting back as if into a chair until thighs parallel floor.",
      "Drive through heels to stand back upright with powerful hip extension."
    ],
    sets: 4,
    reps: 12,
    weightKg: 40,
    restSeconds: 90,
    isFavorite: true,
  },
  {
    id: "ex-6",
    name: "Plank",
    category: "Bodyweight",
    bodyPart: "Abs",
    difficulty: "Beginner",
    equipment: ["Mat"],
    musclesWorked: ["Rectus Abdominis", "Transverse Abdominis", "Obliques"],
    instructions: [
      "Support weight on forearms and toes, elbows stacked under shoulders.",
      "Maintain a flat back, tuck pelvis slightly, and brace core firmly.",
      "Hold steady without sagging hips or arching upper back."
    ],
    sets: 3,
    reps: 60, // seconds
    weightKg: 0,
    restSeconds: 45,
    isFavorite: false,
  },
  {
    id: "ex-7",
    name: "Shoulder Press",
    category: "Strength",
    bodyPart: "Shoulders",
    difficulty: "Intermediate",
    equipment: ["Dumbbells", "Seat"],
    musclesWorked: ["Anterior Delts", "Lateral Delts", "Triceps", "Upper Traps"],
    instructions: [
      "Sit upright with back supported, dumbbells held at ear height.",
      "Press dumbbells directly overhead until arms are extended overhead.",
      "Lower under control back to starting ear-level position."
    ],
    sets: 3,
    reps: 10,
    weightKg: 14,
    restSeconds: 60,
    isFavorite: true,
  },
  {
    id: "ex-8",
    name: "Bicep Curl",
    category: "Strength",
    bodyPart: "Arms",
    difficulty: "Beginner",
    equipment: ["Dumbbells"],
    musclesWorked: ["Biceps Brachii", "Brachialis", "Forearms"],
    instructions: [
      "Stand tall holding dumbbells with underhand supinated grip.",
      "Keep elbows pinned to sides and curl weights towards shoulders.",
      "Squeeze biceps at the top and lower slowly."
    ],
    sets: 3,
    reps: 15,
    weightKg: 10,
    restSeconds: 45,
    isFavorite: true,
  },
  {
    id: "ex-9",
    name: "Tricep Dips",
    category: "Bodyweight",
    bodyPart: "Arms",
    difficulty: "Intermediate",
    equipment: ["Dip Bars / Bench"],
    musclesWorked: ["Triceps", "Chest", "Front Delts"],
    instructions: [
      "Grip parallel bars or edge of bench with arms locked out.",
      "Lower body until elbows reach 90-degree angle.",
      "Push back up to full arm extension."
    ],
    sets: 3,
    reps: 12,
    weightKg: 0,
    restSeconds: 60,
    isFavorite: false,
  },
  {
    id: "ex-10",
    name: "Hip Thrust",
    category: "Strength",
    bodyPart: "Glutes",
    difficulty: "Intermediate",
    equipment: ["Barbell", "Bench"],
    musclesWorked: ["Gluteus Maximus", "Hamstrings", "Adductors"],
    instructions: [
      "Rest upper back against bench with barbell loaded across hips.",
      "Drive through heels and squeeze glutes to lift hips level with torso.",
      "Hold for 1 second at top and lower under control."
    ],
    sets: 4,
    reps: 10,
    weightKg: 50,
    restSeconds: 75,
    isFavorite: false,
  },
  {
    id: "ex-11",
    name: "Deadlift",
    category: "Strength",
    bodyPart: "Full Body",
    difficulty: "Advanced",
    equipment: ["Barbell", "Plates"],
    musclesWorked: ["Hamstrings", "Glutes", "Erector Spinae", "Lats", "Forearms"],
    instructions: [
      "Stand with mid-foot under barbell, feet hip-width apart.",
      "Hinge down and grip bar firmly just outside knees.",
      "Brace core, pull chest tall, and stand up pushing floor away."
    ],
    sets: 4,
    reps: 6,
    weightKg: 80,
    restSeconds: 120,
    isFavorite: true,
  },
  {
    id: "ex-12",
    name: "Russian Twists",
    category: "Bodyweight",
    bodyPart: "Abs",
    difficulty: "Beginner",
    equipment: ["Mat", "Medicine Ball"],
    musclesWorked: ["Obliques", "Transverse Abdominis"],
    instructions: [
      "Sit on floor with knees bent, leaning back at 45 degrees.",
      "Rotate torso from left to right, tapping floor beside hip.",
      "Maintain a proud chest and braced core throughout."
    ],
    sets: 3,
    reps: 20,
    weightKg: 5,
    restSeconds: 45,
    isFavorite: false,
  },
];

export const BODY_PARTS_LIST = [
  { id: "Chest", name: "Chest", subtitle: "Pectorals & Push Power", icon: "🛡️", count: 18 },
  { id: "Back", name: "Back", subtitle: "Lats, Traps & Rhomboids", icon: "🦅", count: 24 },
  { id: "Shoulders", name: "Shoulders", subtitle: "Deltoids & Traps", icon: "🏹", count: 16 },
  { id: "Arms", name: "Arms", subtitle: "Biceps, Triceps & Forearms", icon: "💪", count: 22 },
  { id: "Legs", name: "Legs", subtitle: "Quads, Hamstrings & Calves", icon: "🦵", count: 28 },
  { id: "Abs", name: "Abs", subtitle: "Core & Obliques", icon: "🔥", count: 15 },
  { id: "Glutes", name: "Glutes", subtitle: "Gluteus Max & Hip Drive", icon: "🍑", count: 14 },
  { id: "Full Body", name: "Full Body", subtitle: "Compound & Conditioning", icon: "⚡", count: 30 },
] as const;

export const FEATURED_PROGRAMS: WorkoutProgram[] = [
  {
    id: "prog-1",
    title: "Muscle Building",
    durationWeeks: 8,
    difficulty: "Intermediate",
    description: "Hypertrophy-focused training split designed to maximize lean muscle mass and structural symmetry.",
    enrolledCount: 14200,
    rating: 4.9,
    color: "#FF5A36",
  },
  {
    id: "prog-2",
    title: "Fat Loss Starter",
    durationWeeks: 6,
    difficulty: "Beginner",
    description: "High energy-density circuits combining full-body resistance with steady-state metabolic conditioning.",
    enrolledCount: 22800,
    rating: 4.8,
    color: "#FF8B6B",
  },
  {
    id: "prog-3",
    title: "Strength & Power",
    durationWeeks: 10,
    difficulty: "Advanced",
    description: "Progressive overload system centered around fundamental barbell lifts and neurological peak force.",
    enrolledCount: 9500,
    rating: 4.9,
    color: "#EA4C27",
  },
  {
    id: "prog-4",
    title: "Full Body Transformation",
    durationWeeks: 12,
    difficulty: "All Levels",
    description: "Holistic 3-phase athletic roadmap integrating strength, core stability, and functional mobility.",
    enrolledCount: 31000,
    rating: 5.0,
    color: "#D43812",
  },
];

export const INITIAL_PLANS: WorkoutPlan[] = [
  {
    id: "plan-ppl",
    name: "Push Pull Legs Plan",
    daysPerWeek: 5,
    difficulty: "Intermediate",
    category: "Strength & Hypertrophy",
    activeDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    targetMuscles: ["Chest", "Back", "Legs", "Shoulders", "Arms"],
    isCurrent: true,
    exercises: [
      INITIAL_EXERCISES[0],
      INITIAL_EXERCISES[1],
      INITIAL_EXERCISES[2],
      INITIAL_EXERCISES[6],
      INITIAL_EXERCISES[7],
      INITIAL_EXERCISES[8],
    ],
  },
  {
    id: "plan-ul",
    name: "Upper Lower Split",
    daysPerWeek: 4,
    difficulty: "Beginner",
    category: "Foundational Strength",
    activeDays: ["Mon", "Tue", "Thu", "Fri"],
    targetMuscles: ["Chest", "Back", "Legs", "Abs"],
    isCurrent: false,
    exercises: [
      INITIAL_EXERCISES[1],
      INITIAL_EXERCISES[3],
      INITIAL_EXERCISES[4],
      INITIAL_EXERCISES[5],
    ],
  },
  {
    id: "plan-fb",
    name: "Full Body 3-Day Blast",
    daysPerWeek: 3,
    difficulty: "Beginner",
    category: "Metabolic Conditioning",
    activeDays: ["Mon", "Wed", "Fri"],
    targetMuscles: ["Full Body", "Core"],
    isCurrent: false,
    exercises: [
      INITIAL_EXERCISES[0],
      INITIAL_EXERCISES[4],
      INITIAL_EXERCISES[10],
      INITIAL_EXERCISES[5],
    ],
  },
];

export const INITIAL_MEASUREMENTS: BodyStatMeasurement[] = [
  { id: "m-1", label: "Weight", currentValue: 75.6, unit: "kg", change: -1.2, trend: "down", date: "Today" },
  { id: "m-2", label: "Body Fat", currentValue: 18.5, unit: "%", change: -1.5, trend: "down", date: "Today" },
  { id: "m-3", label: "Muscle Mass", currentValue: 60.2, unit: "kg", change: 1.8, trend: "up", date: "Today" },
  { id: "m-4", label: "Chest", currentValue: 102, unit: "cm", change: 2.0, trend: "up", date: "Today" },
  { id: "m-5", label: "Waist", currentValue: 82, unit: "cm", change: -2.0, trend: "down", date: "Today" },
  { id: "m-6", label: "Arms", currentValue: 36, unit: "cm", change: 1.0, trend: "up", date: "Today" },
  { id: "m-7", label: "Thighs", currentValue: 58, unit: "cm", change: 1.0, trend: "up", date: "Today" },
];
