import {
  PropertyItem,
  MaintenanceTicket,
  TenantInfo,
  RentPaymentEntry,
  VendorContact,
  PropertyDocument,
  UtilityRecord
} from './propertyTypes';

export const INITIAL_PROPERTIES: PropertyItem[] = [
  {
    id: 'prop-lakeview',
    name: 'Lakeview Apartment',
    type: 'Apartment / Condo',
    status: 'Rented Out',
    ownershipType: 'Self-Owned',
    address: 'Lakeside, Ward 6',
    city: 'Pokhara',
    state: 'Gandaki',
    country: 'Nepal',
    pincode: '33700',
    landRegistryNumber: '12-1-45-678',
    areaTotal: 1100,
    areaUnit: 'sq ft',
    builtUpArea: 1100,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    floorNumber: 3,
    totalFloors: 5,
    purchaseDate: '2021-04-12',
    purchasePrice: 18500000,
    currentEstimatedValue: 24500000,
    currency: 'NPR',
    monthlyRent: 50000,
    securityDeposit: 100000,
    occupancyRate: 100,
    nextRentDueDate: '2025-06-01',
    annualMaintenanceCost: 18450,
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'
    ],
    documentsCount: 6,
    propertyTax: 22000,
    taxDueDate: '2025-08-30',
    taxStatus: 'Paid',
    insuranceProvider: 'Siddhartha Premier Insurance',
    insurancePolicyNumber: 'POL-PKR-9921',
    insuranceExpiryDate: '2026-04-10',
    notes: 'Furnished 2BHK with lake-view balcony and covered car parking.',
    isActive: true,
    latitude: 28.2096,
    longitude: 83.9571
  },
  {
    id: 'prop-family-home',
    name: 'Main Family Home',
    type: 'Residential House',
    status: 'Owner-Occupied',
    ownershipType: 'Self-Owned',
    address: 'Deuba Chowk, Budhanilkantha',
    city: 'Kathmandu',
    state: 'Bagmati',
    country: 'Nepal',
    pincode: '44600',
    landRegistryNumber: 'KTM-BNK-8812',
    areaTotal: 1800,
    areaUnit: 'sq ft',
    landArea: 2200,
    builtUpArea: 1800,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    totalFloors: 2,
    purchaseDate: '2019-10-05',
    purchasePrice: 28000000,
    currentEstimatedValue: 39000000,
    currency: 'NPR',
    monthlyRent: 0,
    securityDeposit: 0,
    occupancyRate: 100,
    nextRentDueDate: 'N/A',
    annualMaintenanceCost: 28500,
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'
    ],
    documentsCount: 8,
    propertyTax: 35000,
    taxDueDate: '2025-09-15',
    taxStatus: 'Paid',
    insuranceProvider: 'Himalayan Everest Insurance',
    insurancePolicyNumber: 'POL-HE-11420',
    insuranceExpiryDate: '2026-05-30',
    notes: '2.5 Storey modern house with solar backup and rooftop garden.',
    isActive: true,
    latitude: 27.7667,
    longitude: 85.3667
  },
  {
    id: 'prop-downtown-office',
    name: 'Downtown Office Space',
    type: 'Commercial Office / Space',
    status: 'Rented Out',
    ownershipType: 'Self-Owned',
    address: 'New Road, Ward 22',
    city: 'Kathmandu',
    state: 'Bagmati',
    country: 'Nepal',
    pincode: '44600',
    landRegistryNumber: 'NR-COMM-4419',
    areaTotal: 2500,
    areaUnit: 'sq ft',
    builtUpArea: 2500,
    bathrooms: 1,
    parkingSpots: 4,
    floorNumber: 2,
    totalFloors: 6,
    purchaseDate: '2017-02-18',
    purchasePrice: 38000000,
    currentEstimatedValue: 56000000,
    currency: 'NPR',
    monthlyRent: 85000,
    securityDeposit: 250000,
    occupancyRate: 100,
    nextRentDueDate: '2025-06-05',
    annualMaintenanceCost: 45000,
    photos: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80'
    ],
    documentsCount: 11,
    propertyTax: 68000,
    taxDueDate: '2025-07-20',
    taxStatus: 'Due Soon',
    insuranceProvider: 'Neco Insurance',
    insurancePolicyNumber: 'POL-NC-88402',
    insuranceExpiryDate: '2026-03-15',
    notes: 'Open-plan commercial IT office with dedicated fiber internet and lift.',
    isActive: true,
    latitude: 27.7025,
    longitude: 85.3134
  },
  {
    id: 'prop-green-villa',
    name: 'Green Villa',
    type: 'Villa / Bungalow',
    status: 'Under Renovation',
    ownershipType: 'Self-Owned',
    address: 'Jhamsikhel, Patan',
    city: 'Lalitpur',
    state: 'Bagmati',
    country: 'Nepal',
    pincode: '44700',
    landRegistryNumber: 'LAL-JHM-3301',
    areaTotal: 2200,
    areaUnit: 'sq ft',
    landArea: 3200,
    builtUpArea: 2200,
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 3,
    totalFloors: 2,
    purchaseDate: '2022-08-01',
    purchasePrice: 42000000,
    currentEstimatedValue: 49500000,
    currency: 'NPR',
    monthlyRent: 95000,
    securityDeposit: 200000,
    occupancyRate: 0,
    nextRentDueDate: 'Renovating',
    annualMaintenanceCost: 72000,
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'
    ],
    documentsCount: 4,
    propertyTax: 42000,
    taxDueDate: '2025-10-10',
    taxStatus: 'Paid',
    insuranceProvider: 'Siddhartha Insurance',
    insurancePolicyNumber: 'POL-SI-66710',
    insuranceExpiryDate: '2026-08-01',
    notes: 'Currently undergoing kitchen and exterior facade modernization.',
    isActive: true,
    latitude: 27.6744,
    longitude: 85.3123
  }
];

export const INITIAL_MAINTENANCE_TICKETS: MaintenanceTicket[] = [
  {
    id: 'tkt-12',
    ticketNumber: '#TKT-0012',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Leaking faucet in kitchen',
    description: 'Water is leaking continuously from the kitchen faucet mixer tap. Need to fix washer and cartridge.',
    category: 'Plumbing',
    priority: 'Medium',
    status: 'Assigned',
    reportedDate: '28 Apr 2025',
    reportedTime: '10:30 AM',
    reportedBy: 'Roshan Singh (Tenant)',
    assignedContractorId: 'ven-1',
    assignedContractorName: 'Ram Plumbing Services',
    assignedContractorContact: '+977 9851029384',
    assignedContractorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    assignedDate: '28 Apr 2025, 11:00 AM',
    estimatedCost: 1200,
    currency: 'NPR',
    beforePhotos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80'
    ],
    afterPhotos: [],
    workflowSteps: [
      {
        status: 'Reported',
        label: 'Reported',
        timestamp: '28 Apr 2025, 10:30 AM',
        note: 'Issue submitted by Roshan Singh with photo attachment.',
        actor: 'Roshan Singh',
        completed: true
      },
      {
        status: 'Assigned',
        label: 'Assigned',
        timestamp: '28 Apr 2025, 11:00 AM',
        note: 'Assigned to Ram Plumbing Services (Contractor: Ram Bahadur).',
        actor: 'Property Manager',
        completed: true
      },
      {
        status: 'In Progress',
        label: 'In Progress',
        timestamp: '28 Apr 2025, 02:30 PM',
        note: 'Technician dispatched with replacement ceramic cartridge.',
        actor: 'Ram Bahadur',
        completed: false
      },
      {
        status: 'Completed',
        label: 'Completed',
        timestamp: 'Pending verification',
        note: 'Awaiting completion photo and tenant sign-off.',
        actor: 'System',
        completed: false
      }
    ]
  },
  {
    id: 'tkt-11',
    ticketNumber: '#TKT-0011',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'AC not cooling properly',
    description: 'Master bedroom inverter AC blows warm air. Please check gas pressure and clean condenser coils.',
    category: 'HVAC',
    priority: 'High',
    status: 'In Progress',
    reportedDate: '26 Apr 2025',
    reportedTime: '03:15 PM',
    reportedBy: 'Roshan Singh (Tenant)',
    assignedContractorId: 'ven-2',
    assignedContractorName: 'CoolTech Solutions',
    assignedContractorContact: '+977 9841928374',
    assignedContractorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    assignedDate: '26 Apr 2025, 04:00 PM',
    inProgressDate: '27 Apr 2025, 10:00 AM',
    estimatedCost: 3500,
    currency: 'NPR',
    beforePhotos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80'
    ],
    afterPhotos: [],
    workflowSteps: [
      {
        status: 'Reported',
        label: 'Reported',
        timestamp: '26 Apr 2025, 03:15 PM',
        note: 'Reported temperature drop failure in master bedroom AC.',
        actor: 'Roshan Singh',
        completed: true
      },
      {
        status: 'Assigned',
        label: 'Assigned',
        timestamp: '26 Apr 2025, 04:00 PM',
        note: 'Assigned to CoolTech HVAC Engineers.',
        actor: 'Property Manager',
        completed: true
      },
      {
        status: 'In Progress',
        label: 'In Progress',
        timestamp: '27 Apr 2025, 10:00 AM',
        note: 'Gas refill R32 underway + coil chemical wash.',
        actor: 'CoolTech Technician',
        completed: true
      },
      {
        status: 'Completed',
        label: 'Completed',
        timestamp: 'Scheduled today',
        note: 'Final test run scheduled.',
        actor: 'Technician',
        completed: false
      }
    ]
  },
  {
    id: 'tkt-10',
    ticketNumber: '#TKT-0010',
    propertyId: 'prop-downtown-office',
    propertyName: 'Downtown Office Space',
    title: 'Main circuit breaker tripping',
    description: 'Switchboard 2 on the server rack trips during high load. Load balance needed.',
    category: 'Electrical',
    priority: 'Urgent',
    status: 'Completed',
    reportedDate: '20 Apr 2025',
    reportedTime: '09:00 AM',
    reportedBy: 'Kiran Thapa (Office Manager)',
    assignedContractorId: 'ven-3',
    assignedContractorName: 'Shrestha Electric Works',
    assignedContractorContact: '+977 9801827364',
    assignedContractorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    assignedDate: '20 Apr 2025, 09:30 AM',
    inProgressDate: '20 Apr 2025, 10:15 AM',
    completedDate: '20 Apr 2025, 01:00 PM',
    estimatedCost: 4800,
    finalCost: 4500,
    currency: 'NPR',
    beforePhotos: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80'
    ],
    afterPhotos: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80'
    ],
    workflowSteps: [
      {
        status: 'Reported',
        label: 'Reported',
        timestamp: '20 Apr 2025, 09:00 AM',
        note: 'Emergency breaker trip logged.',
        actor: 'Kiran Thapa',
        completed: true
      },
      {
        status: 'Assigned',
        label: 'Assigned',
        timestamp: '20 Apr 2025, 09:30 AM',
        note: 'Shrestha Electric licensed master electrician dispatched.',
        actor: 'Property Manager',
        completed: true
      },
      {
        status: 'In Progress',
        label: 'In Progress',
        timestamp: '20 Apr 2025, 10:15 AM',
        note: '63A MCB installed and phase balance verified.',
        actor: 'Electrician',
        completed: true
      },
      {
        status: 'Completed',
        label: 'Completed',
        timestamp: '20 Apr 2025, 01:00 PM',
        note: 'Tested with 15kVA load. Stable. Invoice settled.',
        actor: 'Property Manager',
        completed: true
      }
    ]
  }
];

export const INITIAL_TENANTS: TenantInfo[] = [
  {
    id: 'ten-1',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    fullName: 'Roshan Singh',
    phone: '+977 9841882233',
    email: 'roshan.singh@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    occupation: 'Senior Software Engineer',
    emergencyContact: '+977 9812334455 (Father - H. Singh)',
    moveInDate: '2024-01-01',
    leaseStart: '2024-01-01',
    leaseEnd: '2025-12-31',
    monthlyRent: 50000,
    securityDeposit: 100000,
    rentStatus: 'Paid',
    activeAgreementFile: 'Lease_Agreement_Lakeview_2025.pdf',
    notes: 'Always pays on time via eSewa. Keeps property spotless.'
  },
  {
    id: 'ten-2',
    propertyId: 'prop-downtown-office',
    propertyName: 'Downtown Office Space',
    fullName: 'Kiran Thapa',
    phone: '+977 9801998877',
    email: 'kiran@cloudtech.com.np',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    occupation: 'Director, CloudTech Nepal',
    emergencyContact: '+977 9851001122 (Corporate Legal)',
    moveInDate: '2023-06-01',
    leaseStart: '2023-06-01',
    leaseEnd: '2026-05-31',
    monthlyRent: 85000,
    securityDeposit: 250000,
    rentStatus: 'Paid',
    activeAgreementFile: 'Commercial_Lease_NewRoad_2023.pdf',
    notes: '3-year registered corporate tenancy with 5% annual escalation.'
  }
];

export const INITIAL_RENT_PAYMENTS: RentPaymentEntry[] = [
  {
    id: 'rent-may-25',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    tenantName: 'Roshan Singh',
    month: 'May',
    year: 2025,
    amount: 50000,
    dueDate: '2025-05-05',
    paidDate: '2025-05-02',
    paymentMethod: 'eSewa',
    status: 'Paid',
    receiptUrl: 'Receipt_May_2025_Lakeview.pdf'
  },
  {
    id: 'rent-apr-25',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    tenantName: 'Roshan Singh',
    month: 'April',
    year: 2025,
    amount: 50000,
    dueDate: '2025-04-05',
    paidDate: '2025-04-03',
    paymentMethod: 'Bank Transfer',
    status: 'Paid'
  },
  {
    id: 'rent-mar-25',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    tenantName: 'Roshan Singh',
    month: 'March',
    year: 2025,
    amount: 50000,
    dueDate: '2025-03-05',
    paidDate: '2025-03-05',
    paymentMethod: 'eSewa',
    status: 'Paid'
  },
  {
    id: 'rent-comm-may-25',
    propertyId: 'prop-downtown-office',
    propertyName: 'Downtown Office Space',
    tenantName: 'Kiran Thapa (CloudTech)',
    month: 'May',
    year: 2025,
    amount: 85000,
    dueDate: '2025-05-07',
    paidDate: '2025-05-06',
    paymentMethod: 'Bank Transfer',
    status: 'Paid'
  }
];

export const INITIAL_VENDORS: VendorContact[] = [
  {
    id: 'ven-1',
    name: 'Ram Plumbing Services',
    contactPerson: 'Ram Bahadur',
    category: 'Plumbing',
    phone: '+977 9851029384',
    email: 'ramplumbing@gmail.com',
    licenseNumber: 'PL-2345',
    rating: 4.8,
    reviewsCount: 32,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    isPreferred: true
  },
  {
    id: 'ven-2',
    name: 'CoolTech Solutions',
    contactPerson: 'Bikash Shrestha',
    category: 'HVAC',
    phone: '+977 9841928374',
    email: 'contact@cooltechnepal.com',
    licenseNumber: 'HVAC-889',
    rating: 4.6,
    reviewsCount: 18,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    isPreferred: true
  },
  {
    id: 'ven-3',
    name: 'Shrestha Electric Works',
    contactPerson: 'Suman Shrestha',
    category: 'Electrical',
    phone: '+977 9801827364',
    email: 'shrestha.electric@outlook.com',
    licenseNumber: 'EL-1122',
    rating: 4.7,
    reviewsCount: 25,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    isPreferred: true
  },
  {
    id: 'ven-4',
    name: 'ColorCraft Painters',
    contactPerson: 'Dipendra Maharjan',
    category: 'Painting',
    phone: '+977 9841223344',
    email: 'colorcraft.ktm@gmail.com',
    licenseNumber: 'PT-3344',
    rating: 4.5,
    reviewsCount: 14,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80'
  },
  {
    id: 'ven-5',
    name: 'Green Landscape & Garden',
    contactPerson: 'Puspa Rai',
    category: 'Landscaping',
    phone: '+977 9811445566',
    email: 'greenlandscape@gmail.com',
    licenseNumber: 'LS-998',
    rating: 4.6,
    reviewsCount: 21,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80'
  }
];

export const INITIAL_DOCUMENTS: PropertyDocument[] = [
  {
    id: 'doc-1',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Lease Agreement (2025)',
    type: 'Lease',
    fileName: 'Lease_Agreement_Lakeview_2025.pdf',
    fileSize: '2.4 MB',
    uploadDate: '12 Apr 2025',
    expiryDate: '31 Dec 2025',
    fileUrl: '#'
  },
  {
    id: 'doc-2',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Property Deed & Lalpurja',
    type: 'Deed',
    fileName: 'Property_Deed_Lakeview.pdf',
    fileSize: '1.8 MB',
    uploadDate: '10 Mar 2024',
    fileUrl: '#'
  },
  {
    id: 'doc-3',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Comprehensive Insurance Policy',
    type: 'Insurance',
    fileName: 'Insurance_Policy_Siddhartha.pdf',
    fileSize: '1.2 MB',
    uploadDate: '05 Jan 2025',
    expiryDate: '10 Apr 2026',
    fileUrl: '#'
  },
  {
    id: 'doc-4',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Electricity Bill - Apr 2025',
    type: 'Utility Bill',
    fileName: 'NEA_Electricity_Apr2025.pdf',
    fileSize: '0.6 MB',
    uploadDate: '20 Apr 2025',
    fileUrl: '#'
  },
  {
    id: 'doc-5',
    propertyId: 'prop-lakeview',
    propertyName: 'Lakeview Apartment',
    title: 'Repair Invoice - AC Service',
    type: 'Invoice',
    fileName: 'Invoice_CoolTech_Apr2025.pdf',
    fileSize: '0.9 MB',
    uploadDate: '28 Apr 2025',
    fileUrl: '#'
  }
];

export const INITIAL_UTILITY_RECORDS: UtilityRecord[] = [
  {
    id: 'ut-may-25',
    propertyId: 'prop-lakeview',
    month: 'May 2025',
    electricityCost: 3250,
    electricityUnits: 350,
    waterCost: 1120,
    waterVolume: 22000,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 7730
  },
  {
    id: 'ut-apr-25',
    propertyId: 'prop-lakeview',
    month: 'April 2025',
    electricityCost: 3100,
    electricityUnits: 330,
    waterCost: 1180,
    waterVolume: 23500,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 7640
  },
  {
    id: 'ut-mar-25',
    propertyId: 'prop-lakeview',
    month: 'March 2025',
    electricityCost: 2800,
    electricityUnits: 290,
    waterCost: 950,
    waterVolume: 19000,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 7110
  },
  {
    id: 'ut-feb-25',
    propertyId: 'prop-lakeview',
    month: 'February 2025',
    electricityCost: 2600,
    electricityUnits: 270,
    waterCost: 890,
    waterVolume: 17800,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 6850
  },
  {
    id: 'ut-jan-25',
    propertyId: 'prop-lakeview',
    month: 'January 2025',
    electricityCost: 3400,
    electricityUnits: 370,
    waterCost: 1050,
    waterVolume: 21000,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 7810
  },
  {
    id: 'ut-dec-24',
    propertyId: 'prop-lakeview',
    month: 'December 2024',
    electricityCost: 3600,
    electricityUnits: 390,
    waterCost: 1100,
    waterVolume: 22000,
    gasCost: 1860,
    gasUnits: 18,
    internetCost: 1000,
    internetSpeed: '100 Mbps',
    wasteManagementCost: 500,
    totalCost: 8060
  }
];
