import {
  LifeEventItem,
  LifePerson,
  MemoryItem,
  CoupleGoalItem,
  LifeQuoteItem,
  GiftIdeaItem,
  ReminderSettingItem
} from "./types";

export const INITIAL_PEOPLE: LifePerson[] = [
  {
    id: "p-1",
    name: "Roshan Sharma",
    relationship: "Self",
    gender: "Male",
    dateOfBirth: "1994-08-15",
    dateOfBirthBS: "2051-04-30",
    tithiBirth: "Bhadra Shukla Ashtami",
    phone: "+977 9841234567",
    createdAt: "2025-01-01",
  },
  {
    id: "p-2",
    name: "Pooja Sharma",
    relationship: "Partner",
    gender: "Female",
    dateOfBirth: "1996-03-22",
    dateOfBirthBS: "2052-12-09",
    spouseId: "p-1",
    phone: "+977 9849876543",
    notes: "My beloved soulmate ❤️",
    createdAt: "2025-01-01",
  },
  {
    id: "p-3",
    name: "Mom (Shanti)",
    relationship: "Parent",
    gender: "Female",
    dateOfBirth: "1970-05-27",
    dateOfBirthBS: "2027-02-14",
    tithiBirth: "Jestha Krishna Dwitiya",
    notes: "Loves sweet pastries & flowers",
    createdAt: "2025-01-01",
  },
  {
    id: "p-4",
    name: "Dad (Kiran)",
    relationship: "Parent",
    gender: "Male",
    dateOfBirth: "1966-06-02",
    dateOfBirthBS: "2023-02-20",
    createdAt: "2025-01-01",
  },
  {
    id: "p-5",
    name: "Aayush (Best Friend)",
    relationship: "Best Friend",
    gender: "Male",
    dateOfBirth: "1995-06-10",
    createdAt: "2025-01-01",
  },
];

export const INITIAL_EVENTS: LifeEventItem[] = [
  {
    id: "e-1",
    title: "Our Anniversary",
    category: "Anniversary",
    date: "24 May 2025",
    originalYear: 2020,
    daysLeft: 5,
    repeat: "Yearly",
    personId: "p-2",
    personName: "Pooja Sharma",
    relationship: "Partner",
    reminderNotice: "1 Day Before at 9:00 AM",
    reminderEnabled: true,
    notes: "The day we became ours ❤️ 5 magical years together!",
    location: "Pokhara Lakeside Resort",
    color: "#FF5A36",
    tags: ["Love", "Romantic", "Milestone"],
    dateBS: "2082 Jestha 10",
  },
  {
    id: "e-2",
    title: "Mom's Birthday",
    category: "Birthday",
    date: "27 May 2025",
    originalYear: 1970,
    daysLeft: 8,
    repeat: "Yearly",
    personId: "p-3",
    personName: "Mom (Shanti)",
    relationship: "Parent",
    reminderNotice: "1 Day Before at 9:00 AM",
    reminderEnabled: true,
    notes: "Order fresh organic fruit cake & bouquet from local florist",
    location: "Home Celebration",
    color: "#F59E0B",
    tags: ["Family", "Birthday"],
    dateBS: "2082 Jestha 13",
  },
  {
    id: "e-3",
    title: "First Trip Together",
    category: "Special Day",
    date: "30 May 2025",
    originalYear: 2021,
    daysLeft: 11,
    repeat: "Yearly",
    personId: "p-2",
    personName: "Pooja Sharma",
    relationship: "Partner",
    reminderNotice: "2 Days Before at 9:00 AM",
    reminderEnabled: true,
    notes: "Anniversary of our first spontaneous road trip to Nagarkot sunrise point",
    location: "Nagarkot Sunrise Point",
    color: "#10B981",
    tags: ["Travel", "Memories"],
    dateBS: "2082 Jestha 16",
  },
  {
    id: "e-4",
    title: "Dad's Birthday",
    category: "Birthday",
    date: "02 June 2025",
    originalYear: 1966,
    daysLeft: 14,
    repeat: "Yearly",
    personId: "p-4",
    personName: "Dad (Kiran)",
    relationship: "Parent",
    reminderNotice: "1 Day Before at 9:00 AM",
    reminderEnabled: false,
    notes: "Surprise dinner with family relatives",
    color: "#3B82F6",
    tags: ["Family", "Dad"],
  },
  {
    id: "e-5",
    title: "Best Friend Birthday",
    category: "Birthday",
    date: "10 June 2025",
    originalYear: 1995,
    daysLeft: 22,
    repeat: "Yearly",
    personId: "p-5",
    personName: "Aayush",
    relationship: "Best Friend",
    reminderNotice: "1 Day Before at 9:00 AM",
    reminderEnabled: true,
    notes: "Plan gaming weekend & barbecue night",
    color: "#8B5CF6",
    tags: ["Friends", "Celebration"],
  },
  {
    id: "e-6",
    title: "Wedding Day",
    category: "Anniversary",
    date: "18 June 2025",
    originalYear: 2022,
    daysLeft: 30,
    repeat: "Yearly",
    personId: "p-2",
    personName: "Pooja Sharma",
    relationship: "Partner",
    reminderNotice: "7 Days Before at 9:00 AM",
    reminderEnabled: true,
    notes: "Candlelight rooftop dinner & surprise gift exchange",
    color: "#EC4899",
    tags: ["Marriage", "Eternal"],
  },
  {
    id: "e-7",
    title: "Bratabandha Ceremony (Nephew)",
    category: "Cultural & Ritual",
    date: "25 July 2025",
    originalYear: 2025,
    daysLeft: 67,
    repeat: "Once",
    reminderNotice: "5 Days Before",
    reminderEnabled: true,
    notes: "Vedic Sacred Thread ritual in temple",
    tithi: "Shrawan Shukla Panchami",
    color: "#F97316",
  },
  {
    id: "e-8",
    title: "Home Purchase Anniversary",
    category: "Personal Milestone",
    date: "15 August 2025",
    originalYear: 2023,
    daysLeft: 88,
    repeat: "Yearly",
    reminderNotice: "3 Days Before",
    reminderEnabled: true,
    notes: "Housewarming remembrance day",
    color: "#14B8A6",
  },
];

export const INITIAL_MEMORIES: MemoryItem[] = [
  {
    id: "m-1",
    eventId: "e-1",
    eventTitle: "Anniversary Dinner",
    title: "5th Anniversary Dinner Date",
    date: "24 May 2024",
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80",
    caption: "Sunset overlooking the water with champagne toast",
    location: "Lakeview Dining, Pokhara",
    likes: 12,
  },
  {
    id: "m-2",
    eventId: "e-1",
    eventTitle: "Weekend Getaway",
    title: "Mountain Cabin Weekend",
    date: "24 May 2023",
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&fit=crop&q=80",
    caption: "Cozy morning coffee surrounded by pine forests",
    location: "Dhulikhel Resort",
    likes: 18,
  },
  {
    id: "m-3",
    eventId: "e-1",
    eventTitle: "Home Celebration",
    title: "First Anniversary at Our Home",
    date: "24 May 2022",
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&auto=format&fit=crop&q=80",
    caption: "Baking our own strawberry shortcake together",
    location: "Kathmandu Living Room",
    likes: 24,
  },
  {
    id: "m-4",
    eventId: "e-2",
    eventTitle: "Mom's 54th Birthday",
    title: "Mom's Surprise Cake Cutting",
    date: "27 May 2024",
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&auto=format&fit=crop&q=80",
    caption: "Mom smiling with all grandchildren surrounding her",
    location: "Family Garden Patio",
    likes: 15,
  },
  {
    id: "m-5",
    eventId: "e-3",
    eventTitle: "Nagarkot Fog & Sun",
    title: "Chasing Sunrise in Hills",
    date: "30 May 2024",
    type: "photo",
    mediaUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
    caption: "Golden hour glow above the clouds",
    location: "Nagarkot View Tower",
    likes: 31,
  },
];

export const INITIAL_COUPLE_GOALS: CoupleGoalItem[] = [
  {
    id: "g-1",
    title: "Travel to 10 New Places",
    category: "Travel & Adventure",
    currentValue: 7,
    targetValue: 10,
    unit: "places",
    progressPercent: 70,
    status: "active",
    targetDate: "Dec 2025",
    notes: "Next: Mustang & Rara Lake trip",
  },
  {
    id: "g-2",
    title: "Buy Our Dream Home",
    category: "Finance & Lifestyle",
    currentValue: 60,
    targetValue: 100,
    unit: "% fund",
    progressPercent: 60,
    status: "active",
    targetDate: "mid 2026",
    notes: "Down payment savings milestone in progress",
  },
  {
    id: "g-3",
    title: "Save for Our Future",
    category: "Wealth & Investment",
    currentValue: 80,
    targetValue: 100,
    unit: "%",
    progressPercent: 80,
    status: "active",
    targetDate: "Ongoing",
    notes: "Emergency & mutual fund target reached 80%",
  },
  {
    id: "g-4",
    title: "Read 12 Books Together",
    category: "Growth & Mindset",
    currentValue: 5,
    targetValue: 12,
    unit: "books",
    progressPercent: 42,
    status: "active",
    targetDate: "Dec 2025",
    notes: "Currently reading: Atomic Habits & The Psychology of Money",
  },
  {
    id: "g-5",
    title: "Workout Together 3x a Week",
    category: "Health & Fitness",
    currentValue: 6,
    targetValue: 12,
    unit: "weeks streak",
    progressPercent: 50,
    status: "active",
    targetDate: "Weekly",
    notes: "Morning yoga and evening walks",
  },
];

export const INITIAL_QUOTES: LifeQuoteItem[] = [
  {
    id: "q-1",
    quote: "Collect moments, not things. That's what life is all about.",
    author: "Unknown",
    category: "For You",
    isFavorite: true,
  },
  {
    id: "q-2",
    quote: "The best thing to hold onto in life is each other.",
    author: "Audrey Hepburn",
    category: "Love",
    isFavorite: true,
    date: "24 May 2025",
  },
  {
    id: "q-3",
    quote: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    author: "Maya Angelou",
    category: "Love",
    isFavorite: false,
  },
  {
    id: "q-4",
    quote: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    category: "Life",
    isFavorite: false,
  },
  {
    id: "q-5",
    quote: "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.",
    author: "John C. Maxwell",
    category: "Motivation",
    isFavorite: true,
  },
  {
    id: "q-6",
    quote: "Grow old along with me! The best is yet to be.",
    author: "Robert Browning",
    category: "Love",
    isFavorite: false,
  },
];

export const INITIAL_GIFT_IDEAS: GiftIdeaItem[] = [
  {
    id: "gi-1",
    title: "Personalized Photo Frame",
    description: "Capture your most precious memories in handcrafted teak wood or acrylic frame with custom engraved date.",
    category: "For Both",
    priceRange: "$$",
    iconName: "Image",
    tags: ["Keepsake", "Romantic", "Home Decor"],
    isBookmarked: true,
  },
  {
    id: "gi-2",
    title: "Handwritten Love Letter",
    description: "A timeless classic sealed with real botanical wax seal, heartfelt handwritten notes on textured parchment.",
    category: "For Her",
    priceRange: "Free / DIY",
    iconName: "Mail",
    tags: ["Emotional", "Timeless", "DIY"],
    isBookmarked: true,
  },
  {
    id: "gi-3",
    title: "Custom Star Map",
    description: "The exact night sky constellation from the precise location and moment you first met or tied the knot.",
    category: "For Both",
    priceRange: "$$",
    iconName: "Sparkles",
    tags: ["Stargazing", "Astrology", "Wall Art"],
    isBookmarked: false,
  },
  {
    id: "gi-4",
    title: "Experience Together",
    description: "Couples spa massage retreat, helicopter sightseeing tour, or private cooking masterclass.",
    category: "For Both",
    priceRange: "$$$",
    iconName: "Compass",
    tags: ["Adventure", "Luxury", "Memories"],
    isBookmarked: false,
  },
  {
    id: "gi-5",
    title: "Subscription Box",
    description: "Monthly artisanal coffee roast, gourmet chocolates, or mystery date night box shipped right to your door.",
    category: "For Him",
    priceRange: "$$",
    iconName: "Gift",
    tags: ["Monthly", "Surprise", "Gourmet"],
    isBookmarked: false,
  },
  {
    id: "gi-6",
    title: "Engraved Minimalist Watch",
    description: "Sleek automatic timepiece with coordinates of your anniversary location engraved on the back casing.",
    category: "For Him",
    priceRange: "$$$",
    iconName: "Watch",
    tags: ["Accessories", "Timeless", "Luxury"],
    isBookmarked: false,
  },
  {
    id: "gi-7",
    title: "Silk Pajama & Self-Care Set",
    description: "100% pure Mulberry silk sleepwear with lavender aromatherapy candle and organic bath oils.",
    category: "For Her",
    priceRange: "$$",
    iconName: "Heart",
    tags: ["Relaxation", "Comfort", "Wellness"],
    isBookmarked: false,
  },
];

export const INITIAL_REMINDERS: ReminderSettingItem[] = [
  {
    id: "r-1",
    eventTitle: "Our Anniversary",
    eventDate: "24 May 2025",
    noticeTime: "1 Day Before at 9:00 AM",
    enabled: true,
    category: "Anniversary",
  },
  {
    id: "r-2",
    eventTitle: "Mom's Birthday",
    eventDate: "27 May 2025",
    noticeTime: "1 Day Before at 9:00 AM",
    enabled: true,
    category: "Birthday",
  },
  {
    id: "r-3",
    eventTitle: "First Trip Together",
    eventDate: "30 May 2025",
    noticeTime: "2 Days Before at 9:00 AM",
    enabled: true,
    category: "Special Day",
  },
  {
    id: "r-4",
    eventTitle: "Dad's Birthday",
    eventDate: "02 June 2025",
    noticeTime: "1 Day Before at 9:00 AM",
    enabled: false,
    category: "Birthday",
  },
  {
    id: "r-5",
    eventTitle: "Best Friend Birthday",
    eventDate: "10 June 2025",
    noticeTime: "1 Day Before at 9:00 AM",
    enabled: true,
    category: "Birthday",
  },
  {
    id: "r-6",
    eventTitle: "Wedding Day",
    eventDate: "18 June 2025",
    noticeTime: "7 Days Before at 9:00 AM",
    enabled: true,
    category: "Anniversary",
  },
];
